version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - dev
    depends_on:
      - mongoseed

  mongoseed:
    container_name: mongoseed
    build: ./mongoseed
    networks:
      - dev

networks:
  dev:
    driver: bridge
